# Generated by Django 4.0.5 on 2022-06-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False, verbose_name='№')),
                ('order_number', models.IntegerField(editable=False, verbose_name='Order, №')),
                ('cost_usd', models.FloatField(editable=False, verbose_name='cost, $')),
                ('delivery_date', models.DateField(editable=False)),
                ('cost_rub', models.FloatField(editable=False, verbose_name='cost, ₽')),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'order',
            },
        ),
    ]
